#!/usr/bin/python

# style_test.py
#
# Mike Bonnington <mjbonnington@gmail.com>
# (c) 2018-2021
#
# Template for Qt GUI application written in Python
# Uses Qt.py for compatibility with all Python bindings.
#
# Directions for use:
# 
# Create your UI in Qt Designer and save as (e.g) 'style.ui'
# No need to compile your UI with pyside-uic as we load the .ui file directly.
# 
# Save your resources file as (e.g.) 'style.qrc'
# Compile resources to with command: 'pyside-rcc style.qrc -o style_rc.py'
# For compatibility with PySide2, replace 'from [PySide/PyQt] import QtCore'
# with 'from Qt import QtCore'
# 
# Run with command: 'python ./style_test.py'

import os
import sys

from Qt import QtCompat, QtCore, QtGui, QtWidgets
import ui_template as UI

# import ui_chrome_rc  # Import resource file as generated by pyside-rcc
# import rsc_rc  # Import resource file as generated by pyside-rcc - LEGACY


# ----------------------------------------------------------------------------
# Configuration
# ----------------------------------------------------------------------------

cfg = {}

# Set window title and object names
cfg['window_object'] = "styleTestUI"
cfg['window_title'] = "Style Test"

# Set the UI and the stylesheet
cfg['ui_file'] = 'forms/style_test.ui'
# cfg['stylesheet'] = os.environ['IC_STYLESHEET']
cfg['stylesheet'] = "style.qss"  # Set to None to use the parent app's stylesheet

# Other options
# cfg['prefs_file'] = os.path.join(os.environ['IC_USERPREFSDIR'], 'core_prefs.json')
# cfg['store_window_geometry'] = True

# ----------------------------------------------------------------------------
# Begin main application class
# ----------------------------------------------------------------------------

class StyleTestApp(QtWidgets.QMainWindow, UI.TemplateUI):
	"""Main application class."""

	def __init__(self, parent=None):
		super(StyleTestApp, self).__init__(parent)
		self.parent = parent

		self.setupUI(**cfg)

		# Set window flags and other Qt attributes
		self.setWindowFlags(QtCore.Qt.Window)

		# # Restore widget state
		# try:
		# 	self.ui.splitter.restoreState(self.settings.value("splitterSizes")) #.toByteArray())
		# 	#self.ui.renderQueue_treeWidget.header().restoreState(self.settings.value("renderQueueView")) #.toByteArray())
		# except:
		# 	pass

		# Set up about dialog
		about = lambda: self.about(
			app_name=cfg['window_title'], 
			app_version="v1.0.0", 
			description="Test UIs.\n", 
			credits="Principal developer: Mike Bonnington")

		self.show()

		# Load and set stylesheet - workaround for bug in Qt 4.8 where some
		# styles not being applied (including QHeaderView / QTableView) if
		# stylesheet is loaded before ui is displayed.
		# self.stylesheet = cfg['stylesheet']
		# self.loadStyleSheet()

		self.info()

		# Connect signals & slots
		self.ui.actionOpen_UI.triggered.connect(self.openUI)
		self.ui.actionOpen_Stylesheet.triggered.connect(self.openQSS)
		self.ui.actionAbout.triggered.connect(about)

		self.ui.actionQuit.triggered.connect(self.exit)
		self.ui.buttonBox.button(QtWidgets.QDialogButtonBox.Cancel).clicked.connect(self.exit)
		#self.ui.buttonBox.button(QtWidgets.QDialogButtonBox.Ok).clicked.connect(self.loadStyleSheet)

		self.ui.colorChooser_button.setStyleSheet("QWidget { background-color: %s }" %self.col['highlight'].name())
		self.ui.colorChooser_button.clicked.connect(self.setAccentColor)
		self.ui.uiBrightness_slider.setValue(self.col['window'].lightness())
		self.ui.uiBrightness_slider.valueChanged.connect(self.setUIBrightness)
		#self.ui.reloadUI_pushButton.clicked.connect(self.loadUIFile)
		self.ui.reloadStylesheet_pushButton.clicked.connect(self.loadStyleSheet)
		self.ui.unloadStylesheet_pushButton.clicked.connect(self.unloadStyleSheet)
		self.ui.saveStylesheet_pushButton.clicked.connect(self.saveStyleSheet)

		self.ui.loadedUIs_tabWidget.tabCloseRequested.connect(lambda index: self.ui.loadedUIs_tabWidget.removeTab(index))  # Allow tabs to be closed

		# Add 'Sort by' separator label
		label = QtWidgets.QLabel("Sort by:")
		sortBy_separator = QtWidgets.QWidgetAction(self)
		sortBy_separator.setDefaultWidget(label)
		self.ui.menuEdit.insertAction(self.ui.actionName, sortBy_separator)

		# Make 'Sort by' actions mutually exclusive
		alignmentGroup = QtWidgets.QActionGroup(self)
		alignmentGroup.addAction(self.ui.actionName)
		alignmentGroup.addAction(self.ui.actionSize)
		alignmentGroup.addAction(self.ui.actionType)
		alignmentGroup.addAction(self.ui.actionDate)

		# Add 'Other' separator label
		label = QtWidgets.QLabel("Other:")
		other_separator = QtWidgets.QWidgetAction(self)
		other_separator.setDefaultWidget(label)
		other_separator.setEnabled(False)
		self.ui.menuEdit.insertAction(self.ui.actionAttribute, other_separator)

		# Make 'Other' actions mutually exclusive
		otherGroup = QtWidgets.QActionGroup(self)
		otherGroup.addAction(self.ui.actionAttribute)
		otherGroup.addAction(self.ui.actionObject)


	# [Application code goes here]


	def info(self):
		""" Return some version info about Python, Qt, binding, etc.
		"""
		from Qt import __binding__, __binding_version__

		print("Python %d.%d.%d" %(sys.version_info[0], sys.version_info[1], sys.version_info[2]))
		print("%s %s" %(__binding__, __binding_version__))
		print("Qt %s" %QtCore.qVersion())


	def openUI(self):
		"""Load UI into its own tab."""

		ui_file = self.fileDialog('.', fileFilter='UI files (*.ui)')
		# Add and select new tab
		if ui_file:
			ui = QtCompat.loadUi(ui_file)
			tab_id = self.ui.loadedUIs_tabWidget.addTab(ui, os.path.basename(ui_file))
			self.ui.loadedUIs_tabWidget.setCurrentIndex(tab_id)
			self.setupWidgets(ui)
			self.conformFormLayoutLabels(ui)


	def openQSS(self):
		"""Load QSS stylesheet file and apply to UI."""

		qss_file = self.fileDialog('.', fileFilter='Qt Style Sheet files (*.qss)')
		# Load and set stylesheet
		if qss_file:
			self.stylesheet = qss_file
			self.loadStyleSheet()
			self.setWindowTitle(cfg['window_title'] + " - " + os.path.basename(self.stylesheet))


	def exit(self):
		"""Exit the UI."""

		print("Exit the UI.")
		self.ui.hide()
		if __name__ == "__main__":
			sys.exit()


	def closeEvent(self, event):
		"""Event handler for when window is closed."""

		# Store window geometry and state of certain widgets
		self.storeWindow()
		self.settings.setValue("splitterSizes", self.ui.splitter.saveState())
		#self.settings.setValue("renderQueueView", self.ui.renderQueue_treeWidget.header().saveState())

		QtWidgets.QMainWindow.closeEvent(self, event)


if __name__ == "__main__":
	app = QtWidgets.QApplication(sys.argv)

	# Apply application style
	# styles = QtWidgets.QStyleFactory.keys()
	# if 'Fusion' in styles:  # Qt5
	# 	app.setStyle('Fusion')

	# Hack to fix 'etching' on disabled text
	pal = QtWidgets.QApplication.palette()
	#pal.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Text, QtGui.QColor(102, 102, 102))
	pal.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Light, QtGui.QColor(0, 0, 0, 0))
	pal.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, QtGui.QColor(0, 0, 0, 0))
	pal.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, QtGui.QColor(0, 0, 0, 0))
	pal.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, QtGui.QColor(0, 0, 0, 0))
	pal.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, QtGui.QColor(0, 0, 0, 0))
	app.setPalette(pal);

	myApp = StyleTestApp()
	sys.exit(app.exec_())

else:
	myApp = StyleTestApp()
